### ISSUE TITLE
[Bug 🐞]: Background colour too bright when editing text in Black theme 

### ISSUE THREAD

**Issue by benjezzy** [davidsmorais/kuro#72] opened 2022-12-07 01:51 UTC
# Bug Title 🐞

**Describe the bug**
When editing a to-do's name in `black` theme, the background colour is too bright making reading the current text to be edited very hard to read 

**Reproduction Steps**
Steps to reproduce the behavior.
- Create to-do in `black` theme 
- Try to edit to-do's name 

**Expected Behavior**
A different colour instead of white to make it easier to read the current text a user wants to edit 

**Screenshots**
- To-do before editing name: 
![Screenshot_20221207_014644](https://user-images.githubusercontent.com/5735188/206067490-eef481f8-b1e2-4967-a2db-ed9e9b9b1ba6.png)

- Todo whilst editing name: 
![Screenshot_20221207_014823](https://user-images.githubusercontent.com/5735188/206067670-ef1d855a-da4b-483c-aff5-3835c679fd94.png)

**Technical Info (please complete the following information)**
 - OS: Manjaro (Arch-based) 
 - Kuro Version: v 8.1.6

**Additional context**
This also happens in the `dark` theme

---
cc:
@davidsmorais

**Comment by davidsmorais** [comment] 2022-12-07 15:11
Hey @benjezzy :wave: 

Thanks for reporting this and for the detailed error report :pray: 
 I'll take a look and release a fix for this in the next release :rocket:

**Comment by davidsmorais** [comment] 2023-02-13 18:36
@benjezzy closing this due to inactivity and being unable to reproduce. Feel free to re-open and share more info it it still happens :+1:

**Closed by davidsmorais** 2023-02-13 18:36 UTC
Labels: bug🐛
